---

name: Compilation Stage
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_SDK }}
          cache: true

      - name: Build Binary Execution
        run: |
          echo "source code compilation is running..."