name: Code Quality Flow
on:
    workflow_call:
        inputs:
            first_message:
                required: true
                type: string
            second_message:
                required: true
                type: string
            third_message:
                required: true
                type: string
            fourth_message:
                required: true
                type: string

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Go CI Linter
              run: echo "${{ inputs.first_message }}"

    secret-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Secret Scanner
              run: echo "${{ inputs.second_message }}"

    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Dependency Scan
              run: echo "${{ inputs.third_message }}"

    gosec:
        runs-on: gosec
        steps:
            - name: Gosec Scanner
              run: echo "${{ inputs.fourth_message }}"
