name: Code Coverage Flow
on:
    workflow_call:
        inputs:
            GO_SDK:
                required: true
                type: string

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source 🫳🏼
              uses: actions/checkout@v6.0.2
            - name: Setup Go ⚙️
              uses: actions/setup-go@v6
              with:
                  go-version: ${{ inputs.GO_SDK }}
            - name: Run Tests 🧪
              run: make test