name: Code Quality Flow
on:
    workflow_call:
        inputs:
            GO_SDK:
                required: true
                type: string

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v6.0.2
            - name: Go CI Linter
              run: echo "Draft golangci-lint"

    secret-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v6.0.2
            - name: Secret Scanner
              run: echo "Draft secret-scanner"

    dependency-scan:
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.3
    
    sbom-cyclonedx:
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.3

    gosec:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v6.0.2
            - name: Gosec Scanner
              uses: securego/gosec@v2.25.0
              with:
                  args: ./...
