name: Containerization Flow
on:
    workflow_dispatch:
        inputs:
            SOURCE_TO_IMAGE:
                required: true
                type: boolean

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source 🫳🏼
              uses: actions/checkout@v6.0.2
            - name: Containerize 📦
              run: |
                docker build -t ${{ inputs.image }}
              