name: "GitHub Action Workflow - CI Go Language"
description: "Complete CI Pipeline to ensure your Go code is secure and reliable while eliminate your effort to compile"

on:
    workflow_call:
        inputs:
            GO_SDK:
                required: true
                type: string
            GOSEC_PARAMS:
                required: true
                type: string

jobs:
    code-quality:
        uses: nandcep/gawf-go/.github/workflows/ci-code-quality.yml@master
        with:
            GO_SDK: "${{ inputs.GO_SDK }}"
            GOSEC_PARAMS: "${{ inputs.GOSEC_PARAMS }}"
    code-coverage:
        needs: [code-quality]
        uses: nandcep/gawf-go/.github/workflows/ci-code-coverage.yml@master
        with:
            GO_SDK: "${{ inputs.GO_SDK }}"
