name: "GitHub Action Workflow - CI Go Language"
description: "Complete CI Pipeline to ensure your Go code is secure and reliable while eliminate your effort to compile"

on:
    workflow_call:
        inputs:
            GO_SDK:
                required: true
                type: string
            GOSEC_PARAMS:
                required: true
                type: string
            BINARY_NAME:
                required: true
                type: string
            SOURCE_TO_IMAGE:
                required: true
                type: boolean

jobs:
    code-quality:
        uses: nandcep/gawf-go/.github/workflows/ci-code-quality.yml@master
        with:
            GO_SDK: "${{ inputs.GO_SDK }}"
            GOSEC_PARAMS: "${{ inputs.GOSEC_PARAMS }}"
        permissions:
            actions: read          
            security-events: write
            contents: read
    code-coverage:
        needs: [code-quality]
        uses: nandcep/gawf-go/.github/workflows/ci-code-coverage.yml@master
        with:
            GO_SDK: "${{ inputs.GO_SDK }}"
    code-compilation:
        needs: [code-coverage]
        uses: nandcep/gawf-go/.github/workflows/ci-code-compilation.yml@master
        with:
            GO_SDK: "${{ inputs.GO_SDK }}"
            BINARY_NAME: "${{ inputs.BINARY_NAME }}"
